### PR TITLE
Text formatting

### PR DESCRIPTION
**Pull request by mehdichaouch**
Fix bad formatting to make a uniform file.

### CODE REVIEW

**Review by randallkanna — APPROVED** [review]

**Comment by mehdichaouch** [comment]
@randallkanna I've done text formatting fix, so if you are agreed with changes this have to be merged before editing you file again otherwise they'll be again conflict that make this not possible to be merged 😉.

Thanks for this great list 👍

**Review by lodenrogue — APPROVED** [review]

**Comment by mehdichaouch** [comment]
Ready to merge? 🚀

**Comment by mehdichaouch** [comment]
👀

**Comment by mehdichaouch** [comment]
@randallkanna respectfully, did you stop maintaining this repo?

**Comment by mehdichaouch** [comment]
Why did you close this one ?

**Pull request closed without merging**
